### ISSUE TITLE
`::set-output` is deprecated

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/actions-msrv#14]
[`::set-output` is now deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This script should update how it sets outputs.

**Comment by con-mark** [comment]
Hi @spenserblack  I can take this :)

**Comment by spenserblack** [comment]
Wow, that was fast :laughing:
Assigned :smiley:
